#!/usr/bin/env bash

set -euo pipefail

function run_or_dry_run() {
    if [ -n "${DRY_RUN}" ]
    then
        echo "$ ${@}"
    else
        "${@}"
    fi
}

REPOSITORY="${REPOSITORY:-https://github.com/t13a/dotfiles}"
BRANCH="${BRANCH:-master}"
DIRECTORY="${DIRECTORY:-${HOME}/.local/share/dotfiles}"
DRY_RUN="${DRY_RUN:-}"

run_or_dry_run mkdir -p "${DIRECTORY}"
run_or_dry_run git clone -b "${BRANCH}" "${REPOSITORY}" "${DIRECTORY}"
run_or_dry_run "${DIRECTORY}/dotfiles" init
