#!/usr/bin/env bash

set -euo pipefail

VUNDLE_REPOSITORY=https://github.com/VundleVim/Vundle.vim
VUNDLE_DIR="${HOME}/.vim/bundle/Vundle.vim"

mkdir -p "${VUNDLE_DIR}"
[ -e "${VUNDLE_DIR}/.git" ] || git clone "${VUNDLE_REPOSITORY}" "${VUNDLE_DIR}"
vim -c VundleInstall -c exit -c exit
